version: '3.8'
services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - guusta
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - cartola-dev-db

  cartola-dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CARTOLA-FC
    networks:
      - guusta
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: nest-estudo
  #   networks:
  #     - guusta    
networks:
  guusta: