version: '3.8'
services:
  cartola-dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CARTOLA-FC
    networks:
      - guusta
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CARTOLA-FC
    networks:
      - guusta    
networks:
  guusta: